(() => {
'use strict';
const K='samter_demo_financial_v1', S='samter_public_demo_session', Y=2026;
const P=[{id:1,name:'2026 농촌 환경개선 사업'},{id:2,name:'도심 환경정비 사업'},{id:3,name:'시설 현황 조사 사업'}];
const L={CONTRIBUTION_IN:'출자금 납입',CONTRIBUTION_REFUND:'출자금 반환',WORKER_PAYMENT:'수행자 지급',PROJECT_INCOME:'사업수입',PROJECT_EXPENSE:'사업지출',OPERATING_EXPENSE:'운영비',OTHER_INCOME:'기타수입',OTHER_EXPENSE:'기타지출',OPENING_BALANCE:'기초잔액'};
const M=['PROJECT_INCOME','PROJECT_EXPENSE','OPERATING_EXPENSE','OTHER_INCOME','OTHER_EXPENSE','OPENING_BALANCE'];
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch{return structuredClone(d)}};
const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const won=v=>`${Number(v||0).toLocaleString('ko-KR')}원`, pn=id=>P.find(x=>+x.id===+id)?.name||'-';
const dir=(t,f='IN')=>['PROJECT_INCOME','OTHER_INCOME','CONTRIBUTION_IN'].includes(t)?'IN':['PROJECT_EXPENSE','OPERATING_EXPENSE','OTHER_EXPENSE','CONTRIBUTION_REFUND','WORKER_PAYMENT'].includes(t)?'OUT':f;
function seed(){return{next:10,closed:{},rows:[
{id:1,d:'2026-01-08',q:'IN',t:'CONTRIBUTION_IN',a:100000,p:null,x:'김수행 조합원 출자금 납입',r:'CONTRIB-001',auto:true},
{id:2,d:'2026-02-15',q:'IN',t:'PROJECT_INCOME',a:5000000,p:1,x:'OO시청 사업비 1차 입금',r:'CITY-2026-001',auto:false},
{id:3,d:'2026-03-04',q:'OUT',t:'WORKER_PAYMENT',a:150000,p:1,x:'수행자 지급 - 김수행',r:'BANK-20260304-01',auto:true},
{id:4,d:'2026-04-02',q:'IN',t:'CONTRIBUTION_IN',a:200000,p:null,x:'박수행 조합원 출자금 납입',r:'CONTRIB-002',auto:true},
{id:5,d:'2026-05-10',q:'OUT',t:'PROJECT_EXPENSE',a:350000,p:2,x:'현장 소모품 및 차량비',r:'EXP-20260510',auto:false},
{id:6,d:'2026-06-18',q:'OUT',t:'WORKER_PAYMENT',a:180000,p:2,x:'수행자 지급 - 박조합',r:'BANK-20260618-01',auto:true},
{id:7,d:'2026-07-01',q:'OUT',t:'OPERATING_EXPENSE',a:120000,p:null,x:'사무실 운영비',r:'OPS-0701',auto:false},
{id:8,d:'2026-08-12',q:'OUT',t:'CONTRIBUTION_REFUND',a:50000,p:null,x:'탈퇴 조합원 출자금 반환',r:'REFUND-003',auto:true},
{id:9,d:'2026-09-01',q:'IN',t:'PROJECT_INCOME',a:2400000,p:3,x:'OO공단 조사사업 착수금',r:'CORP-0901',auto:false}
]}}
let st=get(K,seed()); if(!st?.rows||!st?.closed)st=seed(); const save=()=>localStorage.setItem(K,JSON.stringify(st)); save();
const sess=()=>get(S,null), closed=y=>!!st.closed[y];
function rows(y,f={}){return st.rows.filter(x=>+x.d.slice(0,4)===+y).filter(x=>!f.m||+x.d.slice(5,7)===+f.m).filter(x=>!f.q||x.q===f.q).filter(x=>!f.p||+x.p===+f.p).sort((a,b)=>b.d.localeCompare(a.d)||b.id-a.id)}
function sum(y,p=null){const a=rows(y,p?{p}:{}), z=q=>a.filter(x=>x.q===q).reduce((s,x)=>s+x.a,0), t=k=>a.filter(x=>x.t===k).reduce((s,x)=>s+x.a,0), i=z('IN'),o=z('OUT');return{in:i,out:o,diff:i-o,n:a.length,worker:t('WORKER_PAYMENT'),contrib:t('CONTRIBUTION_IN'),refund:t('CONTRIBUTION_REFUND'),income:t('PROJECT_INCOME'),expense:t('PROJECT_EXPENSE'),ops:t('OPERATING_EXPENSE')}}
function note(m){const e=document.querySelector('#notice');if(!e)return;e.textContent=m;e.className='notice notice-success';e.hidden=false;setTimeout(()=>e.hidden=true,2200)}
function table(a,c){return `<div class="table-wrap"><table><thead><tr><th>날짜</th><th>입출금</th><th>유형</th><th>사업</th><th>내용</th><th>금액</th><th>기록방식</th><th>관리</th></tr></thead><tbody>${a.map(x=>`<tr><td>${x.d}</td><td><span class="p13-dir p13-${x.q.toLowerCase()}">${x.q==='IN'?'입금':'출금'}</span></td><td><strong>${L[x.t]}</strong></td><td>${esc(pn(x.p))}</td><td>${esc(x.x)}<br><small>${esc(x.r||'')}</small></td><td class="p13-amount">${won(x.a)}</td><td><span class="p13-source ${x.auto?'auto':'manual'}">${x.auto?'자동 기록':'직접 입력'}</span></td><td>${!x.auto&&!c?`<button class="btn btn-small btn-secondary" data-e="${x.id}">수정</button> <button class="btn btn-small btn-secondary" data-d="${x.id}">삭제</button>`:'-'}</td></tr>`).join('')||'<tr><td colspan="8">거래가 없습니다.</td></tr>'}</tbody></table></div>`}
function render(y=Y,f={}){const c=document.querySelector('.content');if(!c)return;const s=sum(y),a=rows(y,f),cl=closed(y),ps=f.p?sum(y,+f.p):null,po=P.map(x=>`<option value="${x.id}" ${+f.p===x.id?'selected':''}>${x.name}</option>`).join('');
c.innerHTML=`<div class="page-heading"><div><span class="eyebrow">MONEY FLOW · PUBLIC DEMO</span><h1>거래·결산</h1><span class="p13-status ${cl?'closed':'open'}">${cl?'마감됨 · 읽기 전용':'OPEN'}</span></div><div class="p13-actions"><label>회계연도<input id="p13-y" type="number" value="${y}"></label><button class="btn btn-secondary" id="p13-csv">CSV</button>${cl?'':'<button class="btn btn-secondary" id="p13-close">연도 마감</button>'}</div></div>
<div class="p13-summary"><section class="panel"><span>총 입금</span><strong>${won(s.in)}</strong></section><section class="panel"><span>총 출금</span><strong>${won(s.out)}</strong></section><section class="panel"><span>거래 차액</span><strong>${won(s.diff)}</strong><small>은행잔액 아님</small></section><section class="panel"><span>거래 건수</span><strong>${s.n}건</strong></section></div>
<section class="panel p13-breakdown"><div class="section-head"><div><h2>유형별 합계</h2></div></div><div class="p13-grid"><div>출자금 납입<strong>${won(s.contrib)}</strong></div><div>출자금 반환<strong>${won(s.refund)}</strong></div><div>수행자 지급<strong>${won(s.worker)}</strong></div><div>사업수입<strong>${won(s.income)}</strong></div><div>사업지출<strong>${won(s.expense)}</strong></div><div>운영비<strong>${won(s.ops)}</strong></div></div></section>
${ps?`<section class="panel p13-project"><div class="section-head"><div><h2>사업별 거래 요약 · ${esc(pn(f.p))}</h2></div></div><div class="p13-grid p13-four"><div>사업 입금<strong>${won(ps.in)}</strong></div><div>사업 출금<strong>${won(ps.out)}</strong></div><div>거래 차액<strong>${won(ps.diff)}</strong></div><div>수행자 지급<strong>${won(ps.worker)}</strong></div></div></section>`:''}
<section class="panel table-panel"><div class="section-head"><div><h2>거래내역</h2></div><span class="count-chip">${a.length}건</span></div><form id="p13-f" class="p13-filter"><label>월<select name="m"><option value="">전체</option>${Array.from({length:12},(_,i)=>i+1).map(m=>`<option ${+f.m===m?'selected':''}>${m}</option>`).join('')}</select></label><label>입출금<select name="q"><option value="">전체</option><option value="IN" ${f.q==='IN'?'selected':''}>입금</option><option value="OUT" ${f.q==='OUT'?'selected':''}>출금</option></select></label><label>사업<select name="p"><option value="">전체</option>${po}</select></label><button class="btn btn-small btn-secondary">조회</button></form>${table(a,cl)}</section>
${cl?'':`<section class="panel p13-entry"><div class="section-head"><div><h2>거래 직접 등록</h2></div><button class="btn btn-primary" id="p13-add">직접 입력</button></div><p>사업수입·사업지출·운영비·기타수입·기타지출·기초잔액을 수동으로 기록합니다.</p></section>`}
<section class="panel p13-reconcile"><div class="section-head"><div><h2>자동 거래 연결 상태</h2></div>${cl?'':'<button class="btn btn-small btn-secondary" id="p13-rec">누락 거래 다시 확인</button>'}</div><div class="p13-grid p13-three"><div>누락<strong>0건</strong></div><div>오류<strong>0건</strong></div><div>마감연도 충돌<strong>0건</strong></div></div><p>출자금 및 수행자 지급 원천기록과 공개 데모 거래원장이 일치합니다.</p></section>`; bind(y,f,a)}
function bind(y,f,a){document.querySelector('#p13-y').onchange=e=>render(+e.target.value,{});document.querySelector('#p13-f').onsubmit=e=>{e.preventDefault();render(y,Object.fromEntries(new FormData(e.currentTarget)))};
document.querySelector('#p13-add')?.addEventListener('click',()=>{const t=prompt(`거래유형\n${M.map((x,i)=>`${i+1}. ${L[x]}`).join('\n')}`,'1'),k=M[(+t||1)-1];if(!k)return;const amount=+prompt('금액','100000');if(!amount)return;const d=prompt('거래일',`${y}-09-05`);if(!d)return;const x=prompt('내용','직접 입력 거래');if(!x)return;const p=+prompt('사업 ID (없으면 0)\n1 농촌환경개선 / 2 도심환경정비 / 3 시설현황조사','0')||null;st.rows.push({id:st.next++,d,q:dir(k),t:k,a:amount,p,x,r:'',auto:false});save();note('직접 입력 거래를 등록했습니다.');render(y,f)});
document.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{const x=st.rows.find(r=>r.id==b.dataset.e);if(!x||x.auto||closed(y))return;const n=+prompt('금액',x.a);if(n)x.a=n;const m=prompt('내용',x.x);if(m!==null)x.x=m;save();render(y,f)});document.querySelectorAll('[data-d]').forEach(b=>b.onclick=()=>{const x=st.rows.find(r=>r.id==b.dataset.d);if(!x||x.auto||closed(y)||!confirm('삭제하시겠습니까?'))return;st.rows=st.rows.filter(r=>r.id!==x.id);save();render(y,f)});
document.querySelector('#p13-rec')?.addEventListener('click',()=>note('누락 거래 0건'));document.querySelector('#p13-close')?.addEventListener('click',()=>{if(!confirm(`${y}년을 마감하면 다시 열 수 없습니다.`))return;st.closed[y]={at:new Date().toISOString()};save();render(y,f)});document.querySelector('#p13-csv').onclick=()=>{const h=['날짜','입출금','유형','사업','내용','금액','기록방식'];const csv='\ufeff'+[h,...a.map(x=>[x.d,x.q,L[x.t],pn(x.p),x.x,x.a,x.auto?'자동 기록':'직접 입력'])].map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n');const u=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),z=document.createElement('a');z.href=u;z.download=`samter-financial-${y}.csv`;document.body.appendChild(z);z.click();z.remove();URL.revokeObjectURL(u)}}
function install(){if(sess()?.role!=='ADMIN')return;const s=document.querySelector('.sidebar');if(!s||s.querySelector('[data-phase13-demo]'))return;const b=document.createElement('button');b.className='side-link';b.dataset.phase13Demo='1';b.textContent='거래·결산';b.onclick=()=>{s.querySelectorAll('.side-link').forEach(x=>x.classList.remove('active'));b.classList.add('active');render()};s.appendChild(b)}
window.SAMTER_PHASE13_DEMO={summarize:sum,render,reset(){st=seed();save();render()}};new MutationObserver(install).observe(document.documentElement,{childList:true,subtree:true});install();
})();
