export const SITE_INFO = Object.freeze({
  serviceName: '삼터', institutionName: 'ㅇㅇ사회적협동조합', representative: '염광선',
  registrationNumber: '정보 준비 중', address: '정보 준비 중', phone: '정보 준비 중',
  email: '정보 준비 중', foundedAt: '정보 준비 중',
});
const NAV_ITEMS = [['about.html','기관소개'],['history.html','연혁'],['leader.html','기관장 소개'],['location.html','오시는 길'],['join.html','조합원 가입']];
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
export function brandMarkup(subtitle='지역의 일과 사람을 잇는 서비스'){return `<span class="samter-logo-frame" aria-hidden="true"><img class="samter-logo-image" src="./assets/samter-mark.png" alt=""></span><span class="samter-wordmark"><strong>삼터</strong><small>${escapeHtml(subtitle)}</small></span>`;}
export function institutionalHeaderMarkup(currentPage=''){const nav=NAV_ITEMS.map(([href,label])=>`<a href="./${href}"${href===currentPage?' aria-current="page"':''}>${label}</a>`).join('');return `<header class="samter-global-header"><a class="samter-global-brand" href="./index.html" aria-label="삼터 홈">${brandMarkup()}</a><nav class="samter-global-nav" aria-label="기관 안내">${nav}<a class="samter-platform-link" href="./app.html">업무 플랫폼</a></nav></header>`;}
export function institutionalFooterMarkup(){return `<footer class="samter-institution-footer"><div class="samter-footer-inner"><div class="samter-footer-brand"><a href="./index.html">${brandMarkup('ㅇㅇ사회적협동조합 서비스 브랜드')}</a><p>공공업무와 지역의 사람을 연결하는 협동 플랫폼</p></div><div class="samter-footer-facts" aria-label="기관 정보"><strong>${SITE_INFO.institutionName}</strong><span>대표자 ${SITE_INFO.representative}</span><span>사업자등록번호 ${SITE_INFO.registrationNumber}</span><span>주소 ${SITE_INFO.address}</span><span>전화 ${SITE_INFO.phone} · 이메일 ${SITE_INFO.email}</span></div><nav class="samter-footer-links" aria-label="기관 및 정책 안내"><a href="./about.html">기관소개</a><a href="./history.html">연혁</a><a href="./leader.html">기관장 소개</a><a href="./location.html">오시는 길</a><a href="./terms.html">이용약관</a><a href="./privacy.html">개인정보 처리방침</a></nav></div><p class="samter-footer-note">현재 공개 데모를 위한 안내입니다. 준비 중인 기관 정보와 정책은 확정 후 갱신됩니다.</p></footer>`;}
function pageName(){const name=globalThis.location?.pathname?.split('/').pop();return name||'index.html';}
function replaceLegacyMark(node){if(node.classList.contains('samter-legacy-mark'))return;node.textContent='';node.classList.add('samter-legacy-mark');node.insertAdjacentHTML('afterbegin','<img class="samter-logo-image" src="./assets/samter-mark.png" alt="">');}
function upgradeMarks(root){const selector='.brand-symbol, .brand-mark, .join-brand > span, .login-emblem';if(root.matches?.(selector))replaceLegacyMark(root);root.querySelectorAll?.(selector).forEach(replaceLegacyMark);}
function enhanceLegacyNavigation(root){const nav=root.querySelector('.site-nav');if(!nav||nav.querySelector('[data-institution-link]'))return;const oldAbout=[...nav.querySelectorAll('a')].find((link)=>link.textContent.trim()==='삼터소개');if(oldAbout)oldAbout.href='./about.html';const join=[...nav.querySelectorAll('a')].find((link)=>link.getAttribute('href')==='./join.html');const location=join||nav.querySelector('.nav-login');for(const [href,label] of NAV_ITEMS.slice(1,4)){const link=document.createElement('a');link.href=`./${href}`;link.textContent=label;link.dataset.institutionLink='';nav.insertBefore(link,location);}}
export function hydrateSiteInfo(root=document){const current=pageName();root.querySelectorAll('[data-samter-site-header]').forEach((node)=>{node.outerHTML=institutionalHeaderMarkup(current);});root.querySelectorAll('[data-samter-site-footer]').forEach((node)=>{node.outerHTML=institutionalFooterMarkup();});upgradeMarks(root);enhanceLegacyNavigation(root);const legacyFooter=root.querySelector('.site-footer');if(legacyFooter)legacyFooter.outerHTML=institutionalFooterMarkup();else if(!root.querySelector('.samter-institution-footer'))root.body?.insertAdjacentHTML('beforeend',institutionalFooterMarkup());if(root===document&&document.body&&!document.body.dataset.samterBrandObserver){document.body.dataset.samterBrandObserver='active';new MutationObserver((mutations)=>mutations.forEach((mutation)=>mutation.addedNodes.forEach((node)=>upgradeMarks(node)))).observe(document.body,{childList:true,subtree:true});}}
if(typeof document!=='undefined'){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>hydrateSiteInfo());else hydrateSiteInfo();}
