// Run against a local server or DEMO_URL; never uses the user's browser profile.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
(async () => {
  const browser = await chromium.launch({headless:true});
  try {
    const page = await browser.newPage({viewport:{width:1440,height:1000}});
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));
    page.on('response', r => { if (r.status() >= 400) errors.push(`${r.status()} ${r.url()}`); });
    page.on('dialog', d => d.accept(d.type() === 'prompt' ? '시연 서비스' : undefined));
    const base = process.env.DEMO_URL || 'http://127.0.0.1:8765/';
    await page.goto(base + 'app.html');
    const login = async (email,password) => {
      if (await page.locator('#logout').count()) await page.locator('#logout').click();
      await page.locator('[name=email]').fill(email);
      await page.locator('[name=password]').fill(password);
      await page.locator('#login-form button').click();
    };
    const click = async name => page.getByRole('button',{name,exact:true}).click();
    const action = async name => page.locator(`[data-p15="${name}"]`).first().click();
    await login('admin@samter.kr','Samter1234!');
    await page.locator('[data-phase13-demo]').click();
    assert.match(await page.locator('.content').innerText(), /거래/);
    await page.locator('[data-phase14-demo]').click();
    assert.match(await page.locator('.content').innerText(), /경영공시/);
    const legacy = await page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([k]) => /financial|disclosure/.test(k))));
    await login('consumer@samter.kr','Consumer1234!');
    await action('order');
    await login('worker@samter.kr','Worker1234!');
    await click('내 서비스 · 마켓 주문관리');
    for (const a of ['accept','start','fulfill']) await action(a);
    await login('consumer@samter.kr','Consumer1234!');
    await action('revision');
    await login('worker@samter.kr','Worker1234!');
    await click('내 서비스 · 마켓 주문관리');
    await action('fulfill');
    await login('consumer@samter.kr','Consumer1234!');
    await action('approve');
    await action('bank');
    assert.match(await page.locator('#notice').innerText(), /송금불가/);
    await action('payment');
    await login('worker@samter.kr','Worker1234!');
    await click('내 서비스 · 마켓 주문관리');
    await action('confirm');
    assert.match(await page.locator('.p15').innerText(), /거래완료/);
    assert.deepEqual(await page.evaluate(() => Object.fromEntries(Object.entries(localStorage).filter(([k]) => /financial|disclosure/.test(k)))),legacy);
    await login('agency@samter.kr','Agency1234!');
    await action('project');
    assert.match(await page.locator('.p15').innerText(), /50%/);
    assert.doesNotMatch(await page.locator('.p15').innerText(), /도심 환경정비|추가 현장자료|김수행|지급 계좌/);
    const downloadEvent = page.waitForEvent('download');
    await action('evidence');
    const download = await downloadEvent;
    assert.match(download.suggestedFilename(), /\.txt$/);
    await page.evaluate(() => { window.print = () => { window.demoPrinted = true; }; });
    await action('report');
    assert.equal(await page.evaluate(() => window.demoPrinted),true);
    await login('agency2@samter.kr','Agency1234!');
    assert.match(await page.locator('.p15').innerText(), /도심 환경정비/);
    assert.doesNotMatch(await page.locator('.p15').innerText(), /농촌 환경개선/);
    await login('admin@samter.kr','Samter1234!');
    await click('발주기관 관리');
    await page.locator('[data-link-project="1"]').selectOption('2');
    await action('evidence-toggle');
    await login('agency@samter.kr','Agency1234!');
    assert.match(await page.locator('.p15').innerText(), /담당 사업 0건/);
    await login('agency2@samter.kr','Agency1234!');
    await page.locator('[data-p15="project"][data-id="1"]').click();
    assert.match(await page.locator('.p15').innerText(), /공개된 증빙이 없습니다/);
    await page.reload();
    assert.match(await page.locator('.p15').innerText(), /담당 사업 2건/);
    await page.setViewportSize({width:390,height:844});
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
    fs.mkdirSync('test-results',{recursive:true});
    await page.screenshot({path:'test-results/phase15-agency-mobile.png',fullPage:true});
    await login('consumer@samter.kr','Consumer1234!');
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth),true);
    await page.screenshot({path:'test-results/phase15-market-mobile.png',fullPage:true});
    await page.goto(base);
    assert.match(await page.locator('body').innerText(), /P15B 공개 데모/);
    await page.goto(base + 'join.html');
    assert.match(await page.locator('body').innerText(), /가입/);
    assert.deepEqual(errors,[]);
    console.log('PASS: P13/P14 regression, complete P15 order, agency isolation/publication/reassignment, download/print, reload, mobile, home/join; no page or HTTP errors.');
  } finally { await browser.close(); }
})().catch(e => {console.error(e); process.exitCode=1;});
